flags:
  send_anonymous_usage_stats: false

default:
  outputs:
    default:
      type: duckdb
      path: local.db
      threads: 1
      attach:
        - alias: ducklake_db
          path: ducklake:sqlite:./storage/metadata.sqlite
  target: default